export const blogs = [
  {
    id: 1,
    question:
      "What is an access token and refresh token? How do they work and where should we store them on the client-side?",
    answer:
      "An access token is used for authentication systems. This token is a credential which is generated by an authentication server when a user is successfully authenticated by the server. On the other hand, a refresh token is a long-lived token that is used to obtain a new access token when the current one expires. After a certain time, this token will expire. The client can use the refresh token to request a new access token from the server without requiring the user to re-enter their credentials.",
  },
  {
    id: 2,
    question: "Compare SQL and NoSQL databases?",
    answer:
      "SQL is the acronym for Structured Query Language, and NoSQL stands for Not Only SQL. They are two types of database management systems with different structures. SQL databases are based on a relational model and use tables with predefined schemas to store and organize data. Examples of SQL databases include MySQL and Oracle Database. On the other hand, NoSQL databases provide a flexible and scalable approach to data storage. There are many data models in NoSQL, such as key-value, document, columnar, and graph. Examples of NoSQL databases include MongoDB and MariaDB.",
  },
  {
    id: 3,
    question: "What is Express.js? What is Nest.js?",
    answer:
      "Express.js is a framework for Node.js that provides a simple and flexible set of features for building web applications and APIs. Nest.js is a progressive, TypeScript-based web application framework built on top of Node.js.",
  },
  {
    id: 4,
    question: "What is MongoDB aggregate and how does it work?",
    answer:
      "MongoDB's aggregate is a powerful framework for performing data operations on collections. It is a NoSQL-based database that allows us to process and transform data using a pipeline of stages.",
  },
];
